### ISSUE TITLE
Failed to convert xcresult bundle from Xcode 12

### ISSUE THREAD

**Issue by maxim4to** [zanizrules/fastlane-plugin-xcresult_to_junit#1]
Failed to convert xcresult bundle from Xcode 12. 

Traceback (most recent call last):
	34: from /usr/local/bin/fastlane:23:in `<main>'
	33: from /usr/local/bin/fastlane:23:in `load'
	32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/bin/fastlane:23:in `<top (required)>'
	31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	28: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	26: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:108:in `block in parsing_binding'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-xcresult_to_junit-0.2.4/lib/fastlane/plugin/xcresult_to_junit/actions/xcresult_to_junit_action.rb:11:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-xcresult_to_junit-0.2.4/lib/fastlane/plugin/xcresult_to_junit/actions/xcresult_to_junit_action.rb:11:in `each'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-xcresult_to_junit-0.2.4/lib/fastlane/plugin/xcresult_to_junit/actions/xcresult_to_junit_action.rb:18:in `block in run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-xcresult_to_junit-0.2.4/lib/fastlane/plugin/xcresult_to_junit/actions/xcresult_to_junit_action.rb:18:in `each'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-xcresult_to_junit-0.2.4/lib/fastlane/plugin/xcresult_to_junit/actions/xcresult_to_junit_action.rb:29:in `block (2 levels) in run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-xcresult_to_junit-0.2.4/lib/fastlane/plugin/xcresult_to_junit/actions/xcresult_to_junit_action.rb:29:in `each'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-xcresult_to_junit-0.2.4/lib/fastlane/plugin/xcresult_to_junit/actions/xcresult_to_junit_action.rb:33:in `block (3 levels) in run'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-xcresult_to_junit-0.2.4/lib/fastlane/plugin/xcresult_to_junit/actions/xcresult_to_junit_action.rb:33:in `each'
/Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-xcresult_to_junit-0.2.4/lib/fastlane/plugin/xcresult_to_junit/actions/xcresult_to_junit_action.rb:64:in `block (4 levels) in run': [!] undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by zanizrules** [comment]
Issue should be resolved in version 0.3.0

I've included a commit from your fork: https://github.com/maxim4to/fastlane-plugin-xcresult_to_junit/commit/832a3829b6541730cdfeb255825387013e1e783c
